[theme]
name = "Default"
version = "0.1.0"
author = "Isa Al Ula"
static_path = "static"
templates_path = "templates"

[theme.templates]
components_path = "components"

[[theme.templates.templates]]
name = "default"

[[theme.templates.components]]
name = "404"

[[theme.templates.components]]
name = "blog"

[[theme.templates.components]]
name = "layout"

[[theme.templates.components]]
name = "navbar"

[[theme.templates.components]]
name = "overlay"